# Generated by Django 4.2.7 on 2023-11-29 21:21

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("email", models.CharField(max_length=250)),
                ("bio", ckeditor.fields.RichTextField(blank=True, null=True)),
                (
                    "profile_pic",
                    models.ImageField(blank=True, null=True, upload_to="profile/"),
                ),
                ("social_email", models.CharField(blank=True, max_length=250)),
                ("social_github", models.CharField(blank=True, max_length=250)),
                ("social_facebook", models.CharField(blank=True, max_length=250)),
                ("social_linkedin", models.CharField(blank=True, max_length=250)),
                ("social_twitter", models.CharField(blank=True, max_length=250)),
                ("social_website", models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("snippet", models.CharField(blank=True, max_length=250)),
                ("body", ckeditor.fields.RichTextField(blank=True, null=True)),
                (
                    "post_img",
                    models.ImageField(blank=True, null=True, upload_to="post/"),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.author"
                    ),
                ),
            ],
        ),
    ]
