# Generated by Django 4.0.1 on 2022-01-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_author_bio_author_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='social_email',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='social_facebook',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='social_github',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='social_linkedin',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
