# Generated by Django 4.0.1 on 2022-01-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_author_social_email_author_social_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='social_twitter',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='social_website',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
